server:
  port: 8091

spring:
  datasource:
    username: sa
    url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE

keycloak:
  server:
    contextPath: /auth
    adminUser:
      username: gilson-admin
      password: pass
    realmImportFile: gilsonbraggion-realm.json
