spring:
  security:
    oauth2:
      client:
        registration:
          custom:
            client-id: ssoClient-1
            client-secret: ssoClientSecret-1
            scope: read,write,openid
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8093/ui-one/login/oauth2/code/custom
        provider:
          custom:
            authorization-uri: http://localhost:8091/auth/realms/gilsonbraggion/protocol/openid-connect/auth
            token-uri: http://localhost:8091/auth/realms/gilsonbraggion/protocol/openid-connect/token
            user-info-uri: http://localhost:8091/auth/realms/gilsonbraggion/protocol/openid-connect/userinfo
            jwk-set-uri: http://localhost:8091/auth/realms/gilsonbraggion/protocol/openid-connect/certs
            user-name-attribute: preferred_username
  thymeleaf:
    cache: false
  cache:
    type: NONE
    
server: 
  port: 8093
  servlet: 
    context-path: /ui-one
    
logging: 
  level: 
    org.springframework: INFO

resourceserver:
  api:
    url: http://localhost:8092/sso-resource-server
              
